<div class="toggle js-toggle-show circle-icon">
<h3 class="toggle_hdg _note">
<button type="button" class="toggle_hdg_inner js-toggle-show_btn" aria-controls="toggle-0" aria-expanded="false">
<div class="hdg_inner_box">
<div class="box_flight_number">JAL3082</div>
<div class="flight-date_box">
